```sql
use.mydb --- mydb를 main으로 잡음

inser into cats -- inser into : 테이블에 넣음 : DB에 저장
-- use mydb; 를 하지 않았다면 inser into mydb.cats
( name, age ) -- name, age 컬럼에 넣어라.
values
('냥이', 7) ; -- value값은 컬럼과 일치해야 함.

inser into cats
(age, name)
values
(3, 'victoria');
-- age 컬럼에 3 입력, name 컬럼에 'victoria' 입력

insert into cats
(name, age)
values
('고양이', 10), ('캣츠', 6), ('Sadie', 4) ; -- 엔터치고 여러줄로 해도 됨.
-- name에 고양이, 캣츠, Sadie / age에 10, 6, 4 입력
```
데이터베이스에 데이터를 넣고 빼고 삭제할 수 있는<br>
테이블 작업하기 전에, 데이터베이스를 알려주고 작업하는 방법<br>
SQL 문의 끝엔 항상 (;) 세미콜론으로 마무리<br>

```SQL
create table cats3 -- cats3 테이블 생성 
( id int not null auto_increment, -- id 컬럼은 int입력, NN(NotNull), AI(자동 증가)
name varchar(20),   -- name컬럼은 텍스트 입력 20자 제한 
breed varchar(20),  -- breed컬럼은 텍스트 입력 20자 제한
age int,            -- age 컬럼은 int입력
primary key(id) );  -- id 컬럼은 pk(주키) 중복X, 유일성, 튜플을 식별을 위한 키

inser into cats3
(name, breed, age)
values
('Ringo', 'Tabby', 4); 
-- name은 Ringo, breed는 Tabby, age는 4 입력
```

```SQL
insert into shirts -- shirts 테이블 선택
(article, color, shirt_size, last_worn)
-- article, color, shirt_size, last_worn 컬럼을 선택
values ('polo shirt', 'Khaki', 'S', 96);
-- article: polo shirt, color: Khaki, shirt_size: S, last_worn: 96 입력

SELECT * FROM shirts_db.shirts ; -- shirts_db.shirts의 컬럼 전체 선택

-- shirts.sql 파일을 실행하여, 데이터를 insert
select *
from shirts; 

-- 모든 셔츠를 조회하되, aticle & color만
select aticle, color
from shirts;

-- M 사이즈의 셔츠에서 shirt_id만 빼고 전체 칼럼을 가져오시오
select article, color, shirt_size, last_worn
from shirts
where shirt_size = 'M';

-- polo 셔츠의 사이즈를 L로 바꾸세요
update shirts
set shirt_size= 'L'
where article = 'polo shirt'; 

-- last worn 이 15인 데이터를 0으로 바꾸세요
update shirts
set last_worn = 0
where last_worn = 15 ;

-- blue 셔츠의 사이즈는 XS로 컬러는 off white로 변경하세요
update shirts
set shirt_size = 'XS', color ='off white'
where color = 'blue';
-- update shirts  -- 이건 안되나?
--  set shirt_size, color = 'S', 'off white' 
-- where color = 'blue';

-- 입은지(last_worn) 200일이 지난 셔츠는 삭제하세요
delete
from shirts
where last_worn > 200;

-- 유행이 지난 tank top는 삭제합니다.
delete
from shirts
where article = 'tank top';

-- 셔츠 테이블의 모든 데이터를 삭제하세요
delete
from shirts;
```